;; This is an example:
;; (defun area (area)
;;   (let (a (read))
;;     (if (string= a "1")
;; 	"You Picked 1")
;;     (if (string= a "2")
;; 	"You Picked 2")))

(defun area ()
       (let (x y)
	 (format t "Enter the x variable~%")
	 (setf x (read))
	 (format t "Enter the y variable~%")
	 (setf y (read))
	 (format t "The answer is~%")
	 (values (* y x))))
