(defun volume ()
  (let (l w h)
    (format t "Enter the Length~%")
    (setf l (read))
    (format t "Enter the Width~%")
    (setf w (read))
    (format t "Enter the Height~%")
    (setf h (read))
    (format t "The Volume is:")
    (values (* l w h))))